### ISSUE TITLE
Project Copy for "TNB Forum"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#243]
**Task**
Using the original project proposal as a template, write the copy/text for the project details page on thenewboston.com

We will not be using the text directly from the GitHub project proposal since that information is written more for the 
project reviewers. The copy/text for the project details page on thenewboston.com is more "marketing" content that is 
mainly intended for website visitors.

This task is to write copy for each of the following sections.

- Overview
- Problem
- Target Market
- Benefit to Network & Community
- Centered around TNB

**Copy Requirements**
- As a general guideline, each section should be ~2-3 sentences long
- Must have proper grammar and be understandable from the perspective of an average website visitor

**Links**
- [Original project proposal](https://github.com/thenewboston-developers/Projects/issues/17)
- [TNB project details page](https://thenewboston.com/projects/d7df9c1c-50c9-4d4c-8ba7-27eff38559ee)

**Comment by kizzi789** [comment]
Account Number: f59c1012073ec8f71b51fb7bfc073aedc1bef0b0f35472864a859deb7eaae9e8

**- Overview:** 
The project aims to create a forum where some users can ask questions and others can answer. People will be rewarded by TNBC based on the number of upvotes they get. It can be one of the platforms for non-coders to earn TNBC. The success of the project can be evaluated on the basis of the number of users who get involved in the forum.


**- Problem:**
Currently, in the TNB Discord, it is hard for users to keep track of the topic of conversation. This platform will solve this problem.


**- Target Market:** 
Everyone who has thenewboston coins and also those who want to earn.


**- Benefit to Network & Community:** 
It will be easy for users and developers to solve the problem they are facing. It will also encourage people to be more active and help others since they will also get rewarded.


**- Centered around TNB:** 
It would reduce the time wasted in solving some problems and will increase productivity and workflow. Also, it will help other people who can't code but still earn some TNBC.

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @kizzi789 
Amount: 400
