### ISSUE TITLE
Project Copy for "Kotlin Multiplaform Mobile SDK"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Marketing#251]
**Task**
Using the original project proposal as a template, write the copy/text for the project details page on thenewboston.com

We will not be using the text directly from the GitHub project proposal since that information is written more for the 
project reviewers. The copy/text for the project details page on thenewboston.com is more "marketing" content that is 
mainly intended for website visitors.

This task is to write copy for each of the following sections.

- Overview
- Problem
- Target Market
- Benefit to Network & Community
- Centered around TNB

**Copy Requirements**
- As a general guideline, each section should be ~2-3 sentences long
- Must have proper grammar and be understandable from the perspective of an average website visitor

**Links**
- [Original project proposal](https://github.com/thenewboston-developers/Projects/issues/169)

**Comment by lirdib** [comment]
Kotlin Multiplatform Mobile is a framework introduced by Jetbrains to share core business logic across platforms such as Android and iOS.  Instead of using cross platform Technologies  we can share the business logic and leverage the native capabilities of Android and iOS for better user experience.
By this project we intend to provime a library for the REST APISs which makes sharing bussines logic easier.
This platform is beng develop to help with the creation of TNB crypto so we are targeting any IOS or Android market aho wants to integrale our cryptocurrency imto thier products.
The opportunity and benefit is to provide SDKs to mobile platforms and unlock our crypto currency in the mobile space. For instance, exchanges such as Coinbase already have mobile SDKs and an app.
It provides the network calls to the API endpoints in the currency network and exposes them as a wrapper library. This reduces the workload for an app to integrate the API endpoints where it would just need to call the repository for the specific API.

**Comment by buckyroberts** [comment]
@Chrisha1212 Payment Due

---

User: @lirdib 
Amount: 400

**Comment by lirdib** [comment]
> @Chrisha1212 Payment Due
> 
> User: @lirdib
> Amount: 400
account number
8f0d58726376de1de96b5d9a2b9693c7aae93e4d7423caa98d285c67ef2176b2
