### ISSUE TITLE
Blog Post: The 5 benefits of trading Cryptocurrencies.

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#338]
**Blog Topic**
Explain 5 benefits of trading Cryptocurrencies.

**Blog Criteria**
- Must be 600-800 words
- Please do research to make sure the information stated is thoroughly accurate
- Please make sure content is understandable to someone who knows nothing about crypto
- Must be proofread by another person
- Must not contain copyrighted material
- Include read time
- Include who wrote it
- Include title
- Include secondary titles within article so people can see how information is chunked out

**Comment by EilyshaKaye** [comment]
The benefits of cryptocurrency trading are:

1. Cryptocurrency volatility. The volatility of cryptocurrencies is part of what makes this market so exciting. Rapid intraday price movements can provide a range of opportunities to traders to go long and short but also come with increased risk. So, if you decide to explore the cryptocurrency market, make sure that you have done your research and developed a risk management strategy.
2. Cryptocurrency market hours. The cryptocurrency market is usually available to trade 24 hours a day, seven days a week because there is no centralised governance of the market. Cryptocurrency transactions take place directly between individuals, on cryptocurrency exchanges all over the world. However, there may be periods of downtime when the market is adjusting to infrastructural updates, or ‘forks’.
3. Improved liquidity. Liquidity is the measure of how quickly and easily a cryptocurrency can be converted into cash, without impacting the market price. Liquidity is important because it brings about better pricing, faster transaction times and increased accuracy for technical analysis.
4. Ability to go long or short. When you buy a cryptocurrency, you are purchasing the asset upfront in that hope that it increases in value. But when you trade on the price of a cryptocurrency, you can take advantage of markets that are falling in price, as well as rising. This is known as going short.
5. Leveraged exposure. As CFD trading is a leveraged product, it enables you to open a position on ‘margin’ – a deposit worth just a fraction of the full value of the trade. In other words, you could gain a large exposure to a cryptocurrency market while only tying up a relatively small amount of your capital.

**Comment by Chrisha1212** [comment]
@EilyshaKaye 
Do you have discord?

**Comment by tspearing** [comment]
@EilyshaKaye, Could this go into a google doc so I can make suggestions for edits?

**Comment by ajinkya-talekar** [comment]
Is it completed or still available?

**Comment by Chrisha1212** [comment]
@ajinkya-talekar you can work on it :)

**Comment by YashovardhanSingh** [comment]
@Chrisha1212 https://blogs-for-tnb.blogspot.com/2021/09/the-5-benefits-of-trading.html

**Comment by Chrisha1212** [comment]
> @Chrisha1212 https://blogs-for-tnb.blogspot.com/2021/09/the-5-benefits-of-trading.html

Will review this.

**Comment by YashovardhanSingh** [comment]
38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by Chrisha1212** [comment]
> 38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6
requesting for access.

**Comment by YashovardhanSingh** [comment]
@Chrisha1212 What?
