### ISSUE TITLE
Project Logo for "tnbeverything.com"

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Marketing#362]
**Task**
Create a logo for the "tnbeverything.com
" project that will be displayed alongside the project on 
[thenewboston.com/projects](https://thenewboston.com/projects)

**Image Specs**
Size: 64 x 64 | 256 x 256 | 512 x 512
Format: JPG or PNG

**Examples**
![](https://i.imgur.com/7TU6Lhb.jpg)
![](https://i.imgur.com/WKx6YxK.jpg)

**Links**
- [Project Proposal](http://example.com)

**Comment by stweyel** [comment]
Not sure why this issue is opened. There was already a logo provided.
https://github.com/stweyel/tnbuser.com-tnbeverything.com/blob/main/logo.png
![grafik](https://user-images.githubusercontent.com/25363181/126865219-40e96860-fc54-46fe-8c4e-42872bf46607.png)

Project Account
3a115cb6d87edb299e0ca95393465d171768bb5c2c08c4b27e1cfb4c3141f8ec

**Comment by stweyel** [comment]
Update:
![logo64](https://user-images.githubusercontent.com/25363181/126965878-7e7af4dc-b36b-41b8-8ee5-c3a44f980e6b.png)
![logo256](https://user-images.githubusercontent.com/25363181/126965880-2a3ef210-20d9-4f2d-bcc9-28d637694a4e.png)
![everything512](https://user-images.githubusercontent.com/25363181/126965882-d67eebf6-2aff-441e-b5d9-5820db3ab94b.png)


94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d
